# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZapPretty < Formula
  desc "A tiny binary to pretty-print Zap production JSON lines"
  homepage "https://github.com/maoueh/zap-pretty"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.0/zap-pretty_0.3.0_macOS_arm64.tar.gz"
      sha256 "ab86cc4f9dc426d7c6d5a4647020540c0387b9be96810b4e8760b081829b1ae8"

      def install
        bin.install "zap-pretty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.0/zap-pretty_0.3.0_macOS_x86_64.tar.gz"
      sha256 "4d8834399f8194cce01c4263df9793ae252babfb6858d912e9a209237e672a37"

      def install
        bin.install "zap-pretty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.0/zap-pretty_0.3.0_linux_x86_64.tar.gz"
      sha256 "0264d7d319343024b590fa855861c280976f65bdce7be9ad187c6df6ca6f95d4"

      def install
        bin.install "zap-pretty"
      end
    end
  end
end
